### ISSUE TITLE
Post user events to Google Pub/Sub

### ISSUE THREAD

**Issue by shaygeko** [thecodegram/codegram#31]
To enable integration with other platforms, e.g., discord bots, we should start posting our user events to Google Pub/Sub.
This allows for any other microservice we create down the line to easily start listening to the topic

**Comment by ShayGeko** [comment]
To enable integration with other platforms, e.g., discord bots, we should start posting our user events to Google Pub/Sub. 
This allows for any other microservice we create down the line to easily start listening to the topic,
